### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thatoddmailbox** [nywillb/schedulesplus#3]
(see title)

**Comment by RobotXLabs** [comment]
@nywillb MIT?

**Comment by thatoddmailbox** [comment]
@RobotXLabs probably, but @nywillb has to add it because he wrote some code and we all have to agree on one license.

**Comment by nywillb** [comment]
@thatoddmailbox, @RobotXLabs: MIT it is!

**Comment by RobotXLabs** [comment]
Okay!
